export const SUGGESTED_CATEGORIES: string[] = [
  "Web",
  "Web3",
  "AI",
  "Mobile",
  "DevOps",
  "Cloud",
  "Cybersecurity",
  "Data Science",
  "Machine Learning",
  "Blockchain",
  "Design",
  "UI/UX",
  "Product Management",
  "Startup",
  "Fintech",
  "EdTech",
  "HealthTech",
  "Game Development",
  "AR/VR",
  "IoT",
  "Open Source",
  "Software Engineering",
  "Backend",
  "Frontend",
  "Fullstack",
  "Networking",
  "Hackathon",
  "Tech Community",
  "Digital Marketing",
  "Career",
  "Women in Tech",
  "AI Safety",
  "Tech Policy",
  "Innovation",
  "Research",
  "Cloud Native",
  "Serverless",
  "Entrepreneurship",
];
